---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: iamcustomrolesampleproject
  namespace: iac
spec:
  title: Example Project-Level Custom Role
  description: This role only contains two permissions - publish and update
  permissions:
    - pubsub.topics.publish
    - pubsub.topics.update
  stage: GA
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-sample-projectrole
  namespace: iac
spec:
  member: serviceAccount:iamcustomrole-dep-project@jvillarreal-sandbox-360616.iam.gserviceaccount.com
  role: projects/jvillarreal-sandbox-360616/roles/iamcustomrolesampleproject
  resourceRef:
    kind: PubSubTopic
    name: containercluster-dep-vpcnative
    namespace: iac
    apiVersion: pubsub.cnrm.cloud.google.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: iamcustomrole-dep-project
  namespace: iac
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: iamserviceaccountkey-sample
  namespace: iac
  labels:
    label-one: "value-one"
spec:
  publicKeyType: TYPE_X509_PEM_FILE
  keyAlgorithm: KEY_ALG_RSA_2048
  privateKeyType: TYPE_GOOGLE_CREDENTIALS_FILE
  serviceAccountRef:
    name: iamcustomrole-dep-project