---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-projectrole
  namespace: iac
spec:
  member: serviceAccount:iamcustomrole-dep-project@config-conector-sample.iam.gserviceaccount.com
  role: projects/config-conector-sample/roles/cutomroletestargo
  resourceRef:
    kind: PubSubTopic
    name: containercluster-dep-vpcnative
    namespace: iac
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1