---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvillarreal-wireguard
  namespace: default
  labels:
    app: wireguard
    dev: jvillarreal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      tolerations:
        - key: "wireguard"
          operator: "Exists"
      # nodeSelector:
      #   wireguard: "true"
      containers:
      - name: wireguard
        image: ghcr.io/linuxserver/wireguard
        envFrom:
        - configMapRef:
            name: jvillarreal-wireguard-configmap 
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true
        volumeMounts:
          - name: wg-config
            mountPath: /config
          - name: host-volumes
            mountPath: /lib/modules
        ports:
        - containerPort: 51820
          protocol: UDP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: jvillarreal-claim-wireguard  
        - name: host-volumes
          hostPath:
            path: /lib/modules
            type: Directory
...
