---
kind: Service
apiVersion: v1
metadata:
  name: wireguard-service
  namespace: default
  labels:
    app: wireguard
    dev: jvillarreal
spec:
  type: NodePort
  ports:
  - port: 51820
    nodePort: 31899
    protocol: UDP
    targetPort: 51820
  selector:
    app: wireguard
...
