projectRef: jvillarreal-sandbox-demo
serviceAccount: devops-robot
serviceusage:
  - cloudasset.googleapis.com
  - cloudbilling.googleapis.com
  - serviceusage.googleapis.com
  - secretmanager.googleapis.com
  - pubsub.googleapis.com
  - sourcerepo.googleapis.com
  - cloudbuild.googleapis.com
  - artifactregistry.googleapis.com
  - cloudfunctions.googleapis.com
configManagement:
  sourceFormat: "unstructured"
  clusterName: sauron
  enableMultiRepo: true
  enableLegacyFields: true
  git:
    proxy: {}
    syncRepo: "git@github.com:Lapeyus/IDP.git"
    syncBranch: "main"
    policyDir: "configsync/"
    syncWait: 15
    syncRev: "HEAD"
    secretType: "ssh"
  hierarchyController: {}
  policyController:
    enabled: false
    auditIntervalSeconds: 15
    exemptableNamespaces:
    - anthos-identity-service
    - cnrm-system
    - config-management-monitoring
    - config-management-system
    - configconnector-operator-system
    - gatekeeper-system
    - kube-node-lease
    - kube-public
    - kube-system
    - resource-group-system
    logDeniesEnabled: true
    monitoring:
      backends:
      - prometheus
      - cloudmonitoring
    mutation:
      enabled: true
    referentialRulesEnabled: true
    templateLibraryInstalled: true
  preventDrift: true