---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: remotesecretstore
  namespace: {{ .Values.clusterNamespace }}
spec:
  provider:
      gcpsm:
        projectID: {{ .Values.projectID }}
        auth:
            secretRef:
              secretAccessKeySecretRef:
                name: external-secrets-identity
                key: key.json
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: external-secrets-identity
  labels:
    label-one: "demo"
spec:
  publicKeyType: TYPE_X509_PEM_FILE
  keyAlgorithm: KEY_ALG_RSA_2048
  privateKeyType: TYPE_GOOGLE_CREDENTIALS_FILE
  serviceAccountRef:
    name: external-secrets-identity