---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-identity
  namespace: {{ .Values.clusterNamespace }}
  annotations: #{{ .Values.gcpServiceAccount }}
    iam.gke.io/gcp-service-account: "external-secrets-identity@{{ .Values.projectID }}.iam.gserviceaccount.com"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectID }}
  name: external-secrets-identity
spec:
  displayName: Secret Manager Service Account
---
apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectID }}
  name: secretmanager-workloadidentity
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: external-secrets-identity
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:[PROJECT_ID].svc.id.goog[{{ .Values.clusterNamespace }}/external-secrets-identity]
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectID }}
  name: external-secrets-identity
spec:
  bindings:
  - members:
    - member: serviceAccount:external-secrets-identity@{{ .Values.projectID }}.iam.gserviceaccount.com
    role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    external: 'projects/{{ .Values.projectID }}'
    kind: Project

# ---
# apiVersion: iam.cnrm.cloud.google.com/v1beta1
# kind: IAMPolicy
# metadata:
#   annotations:
#     cnrm.cloud.google.com/project-id: {{ .Values.projectID }}
#   name: secretmanager-workloadidentity
# spec:
#   resourceRef:
#     kind: IAMServiceAccount
#     name: external-secrets-identity@{{ .Values.projectID }}.iam.gserviceaccount.com
#     apiVersion: iam.cnrm.cloud.google.com/v1beta1
#   bindings:
#     - role: roles/iam.workloadIdentityUser
#       members:
#         - serviceAccount:{{ .Values.projectID }}.svc.id.goog[{{ .Values.clusterNamespace }}/external-secrets-identity]