---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-identity
  namespace: {{ .Values.clusterNamespace }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.gcpServiceAccount }}@{{ .Values.projectID }}.iam.gserviceaccount.com"
# ---
# apiVersion: iam.cnrm.cloud.google.com/v1beta1
# kind: IAMServiceAccount
# metadata:
#   annotations:
#     cnrm.cloud.google.com/project-id: {{ .Values.projectID }}
#   name: secretmanager-workloadidentity
# spec:
#   displayName: Secret Manager Service Account
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: secretmanager-workloadidentity
#   annotations:
#     iam.gke.io/gcp-service-account: secretmanager-workloadidentity@{{ .Values.projectID }}.iam.gserviceaccount.com
# ---
# apiVersion: iam.cnrm.cloud.google.com/v1beta1
# kind: IAMPolicy
# metadata:
#   annotations:
#     cnrm.cloud.google.com/project-id: {{ .Values.projectID }}
#   name: secretmanager-workloadidentity
# spec:
#   resourceRef:
#     kind: IAMServiceAccount
#     name: devops-robot@{{ .Values.projectID }}.iam.gserviceaccount.com
#     apiVersion: iam.cnrm.cloud.google.com/v1beta1
#   bindings:
#     - role: roles/iam.workloadIdentityUser
#       members:
#         - serviceAccount:{{ .Values.projectID }}.svc.id.goog[default/secretmanager-workloadidentity]
# ---
# apiVersion: iam.cnrm.cloud.google.com/v1beta1
# kind: IAMPolicyMember
# metadata:
#   annotations:
#     cnrm.cloud.google.com/project-id: {{ .Values.projectID }}
#   name: secretmanager-admin
# spec:
#   member: serviceAccount:secretmanager-workloadidentity@{{ .Values.projectID }}.iam.gserviceaccount.com
#   role: roles/secretmanager.admin
#   resourceRef:
#     kind: Project
#     external: projects/{{ .Values.projectID }}
#     apiVersion: cloudresourcemanager.googleapis.com/v1beta1

