---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-identity
  namespace: {{ .Values.clusterNamespace }}
  annotations:
    iam.gke.io/gcp-service-account: "external-secrets-identity@{{ .Values.projectID }}.iam.gserviceaccount.com"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectID }}
  name: external-secrets-identity
  namespace: {{ .Values.clusterNamespace }}
spec:
  displayName: Secret Manager Service Account
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectID }}
  name: external-secrets-identity
  namespace: {{ .Values.clusterNamespace }}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: external-secrets-identity
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{ .Values.projectID }}.svc.id.goog[{{ .Values.clusterNamespace }}/external-secrets-identity]
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectID }}
  name: external-secrets-identity
  namespace: {{ .Values.clusterNamespace }}
spec:
  bindings:
  - members:
    - member: serviceAccount:external-secrets-identity@{{ .Values.projectID }}.iam.gserviceaccount.com
    role: roles/editor
  - members:
    - member: serviceAccount:external-secrets-identity@{{ .Values.projectID }}.iam.gserviceaccount.com
    role: roles/secretmanager.secretAccessor
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    external: 'projects/{{ .Values.projectID }}'
    kind: Project
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: external-secrets-identity
  labels:
    label-one: "demo"
spec:
  publicKeyType: TYPE_X509_PEM_FILE
  keyAlgorithm: KEY_ALG_RSA_2048
  privateKeyType: TYPE_GOOGLE_CREDENTIALS_FILE
  serviceAccountRef:
    name: external-secrets-identity