# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: external-secrets-identity
#   namespace: {{ .Values.clusterNamespace }}
#   annotations:
#     iam.gke.io/gcp-service-account: "{{ .Values.gcpServiceAccount }}@{{ .Values.projectID }}.iam.gserviceaccount.com"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore #SecretStore
metadata:
  name: gcpsecretstore
  namespace: {{ .Values.clusterNamespace }}     
spec:
  provider:
      gcpsm:
        projectID: {{ .Values.projectID }}
        auth:
          workloadIdentity:
            clusterLocation: {{ .Values.clusterLocation }}
            clusterName: {{ .Values.clusterName }}
            serviceAccountRef:
              name: secretmanager-workloadidentity
              namespace: {{ .Values.clusterNamespace }}
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore #SecretStore
# metadata:
#   name: gcpsecretstore2
#   namespace: {{ .Values.clusterNamespace }}     
# spec:
#   provider:
#       gcpsm:
#         projectID: {{ .Values.projectID }}
#         auth:
#             secretRef:
#               secretAccessKeySecretRef:
#                 name: gcpsm-secret
#                 key: secret-access-credentials
#                 namespace: {{ .Values.clusterNamespace }}     
