{{- $dot := . -}}
{{- range $secrets := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secrets.key }}-setter
data:
  secretData: YnkK
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ $dot.Values.projectID }}
  name: {{ $secrets.key }}
spec:
  replication:
    automatic: true
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ $dot.Values.projectID }}
  name: {{ $secrets.key }}v1
spec:
  enabled: true
  secretData:
    valueFrom:
      secretKeyRef:
        key: secretData
        name: {{ $secrets.key }}-setter
  secretRef:
    name: {{ $secrets.key }}
...
{{- end }}

