---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsecretstore
  namespace: {{ .Values.clusterNamespace }}     
spec:
  provider:
      gcpsm:
        projectID: {{ .Values.projectID }}
        auth:
          workloadIdentity:
            clusterLocation: {{ .Values.clusterLocation }}
            clusterName: {{ .Values.clusterName }}
            serviceAccountRef:
              name: external-secrets-identity
              namespace: {{ .Values.clusterNamespace }}
...
