---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore #SecretStore
metadata:
  name: gcpsecretstore
  namespace: {{ .Values.clusterNamespace }}     
spec:
  provider:
      gcpsm:
        projectID: {{ .Values.projectID }}
        auth:
          workloadIdentity:
            clusterLocation: {{ .Values.clusterLocation }}
            clusterName: {{ .Values.clusterName }}
            serviceAccountRef:
              name: external-secrets-identity
              namespace: {{ .Values.clusterNamespace }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore #SecretStore
metadata:
  name: gcpsecretstore2
  namespace: {{ .Values.clusterNamespace }}     
spec:
  provider:
      gcpsm:
        projectID: {{ .Values.projectID }}
        auth:
            secretRef:
              secretAccessKeySecretRef:
                name: external-secrets-identity
                key: key.json
                namespace: {{ .Values.clusterNamespace }}     
