---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  labels:
    label-one: "value-one"
  name: computefirewall-sample-allow
  namespace: iac
spec:
  allow:
    - protocol: udp
      ports:
        - "80"
  networkRef:
    name: containercluster-dep-vpcnative
  sourceTags:
    - "web"