# apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
# kind: CloudBuildTrigger
# metadata:
#   annotations:
#     cnrm.cloud.google.com/project-id: config-conector-sample
#   name: cloudbuildtrigger-idp
# spec:
#   description: Cloud Build Trigger for building the master branch
#   disabled: false
#   github:
#     owner: Lapeyus
#     name: IDP
#     push:
#       branch: main
#   ignoredFiles:
#     - "**/*.md"
#   includedFiles:
#     - "/**"
#     - "envs/**"
#   substitutions:
#     "_SERVICE_NAME": "service-name"
#     "_LOCATION": "us-central1"
#     "_REGISTRY": "artifactregistryrepository"
#   build:
#     images: ["gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"]
#     tags: ["team-a", "service-b"]
#     timeout: 1800s
#     step:
#       - name: 'gcr.io/cloud-builders/docker'
#         args: ['build', 
#               '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA', 
#               "-f", "Dockerfile", 
#               "."]
#       - name: 'gcr.io/cloud-builders/docker'
#         args: ['build', 
#               '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REGISTRY}/${_SERVICE_NAME}:$COMMIT_SHA', 
#               "-f", "Dockerfile", 
#               "."]
#       - name: 'gcr.io/cloud-builders/docker'
#         args: ['push', 
#               '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REGISTRY}/${_SERVICE_NAME}:$COMMIT_SHA']