---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: git-creds
spec:
  replication:
    automatic: true
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: git-creds
spec:
  enabled: true
  secretRef:
    name: git-creds
  secretData:
    valueFrom:
      secretKeyRef:
        key: ssh
        name: git-creds