apiVersion: v1
kind: Pod
metadata:
  name: "policy-violation"
  namespace: default
spec:
  containers:
  - envFrom:
    - configMapRef:
        name: jvillarreal-wireguard-configmap
    image: ghcr.io/linuxserver/wireguard
    imagePullPolicy: Always
    name: wireguard
    ports:
    - containerPort: 51821
      protocol: UDP
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_MODULE
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: wg-config
    - mountPath: /lib/modules
      name: host-volumes
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bs9dm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-argo-argo-node-pool-8e2b1da4-znmb
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: wireguard
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: wg-config
    persistentVolumeClaim:
      claimName: jvillarreal-claim-wireguard
  - hostPath:
      path: /lib/modules
      type: Directory
    name: host-volumes
  - name: kube-api-access-bs9dm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
