---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: git-creds
spec:
  replication:
    automatic: true
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: git-creds
  namespace: config-management-system
spec:
  enabled: true
  secretRef:
    name: git-creds
    namespace: config-management-system
  secretData:
    valueFrom:
      secretKeyRef:
        key: ssh
        name: git-creds

# ---
# apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
# kind: SecretManagerSecretVersion
# metadata:
#   annotations:
#     cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
#   name: sensitive1v1
# spec:
#   enabled: true
#   secretData:
#     valueFrom:
#       secretKeyRef:
#         key: secretData
#         name: placeholder
#   secretRef:
#     name: placeholder
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: placeholder
# data:
#   secretData: aGkK
