# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: wireguard
#   namespace: default
# spec:
#   destination:
#     namespace: default
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     directory:
#       jsonnet: {}
#       recurse: true
#     path: helm/wireguards
#     repoURL: git@github.com:Lapeyus/IDP.git
#     targetRevision: argo
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     retry:
#       backoff:
#         duration: 5s
#         factor: 2
#         maxDuration: 3m0s
#       limit: 2
#     syncOptions:
#       - Replace=true
#       - Validate=true
#       - CreateNamespace=true
#       - PrunePropagationPolicy=foreground
#       - PruneLast=true
#       - ApplyOutOfSyncOnly=true

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
