---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jvillarreal-claim-wireguard 
  namespace: default
  labels:
    app: wireguard
    dev: jvillarreal
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
...