apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configconnector
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: 'secrets[0].key'
          value: clusters
        - name: 'secrets[0].name'
          value: clusters
        - name: 'secrets[0].secretKey'
          value: clusters
    path: helm/configconnector
    repoURL: git@github.com:Lapeyus/IDP.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
    - Replace=false