apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage
  namespace: default
spec:
  destination:
    name: ""
    namespace: iac
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: gcp/stage
    repoURL: git@github.com:Lapeyus/IDP.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
    - Validate=false
    - RespectIgnoreDifferences=true
    - PruneLast=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - Replace=false
    - PrunePropagationPolicy=foreground
