projectID: config-conector-sample
# name of the cluster region
clusterLocation: us-central1
# name of the GKE cluster
clusterName: sauron
clusterNamespace: default
gcpServiceAccount: devops-robot
refreshInterval: "5s"
secrets: []
  # - key: cluster
  #   name: cluster
  #   secretKey: cluster