---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-demo
  name: autopilot
spec:
  description: An autopilot cluster.
  enableAutopilot: true
  location: us-central1
  releaseChannel:
    channel: REGULAR