---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: iampolicymember-sample-projlevel
spec:
  member: serviceAccount:iampolicymember-dep-projlevel@jvillarreal-sandbox-360616.iam.gserviceaccount.com
  role: roles/storage.admin
  resourceRef:
    kind: Project
    external: projects/jvillarreal-sandbox-360616
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: iampolicymember-dep-projlevel
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: iampolicymember-sample-projlevels
spec:
  member: user:joseph.villarreal@66degrees.com
  role: roles/storage.admin
  resourceRef:
    kind: Project
    external: projects/jvillarreal-sandbox-360616