---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: 2
spec:
  # memberFrom:
  #   serviceAccountRef:
  #     name: devops-robot
  member: serviceAccount:devops-robot@jvillarreal-sandbox-360616.iam.gserviceaccount.com
  role: roles/editor
  resourceRef:
    kind: PubSubTopic
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    name:  pubsubsubscription-dep
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: iampolicymember-memberref
spec:
  # memberFrom:
  #   serviceAccountRef:
  #     name: devops-robot
  member: user:jvillarreal@qwinix.io
  role: roles/editor
  resourceRef:
    kind: PubSubTopic
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    name:  pubsubsubscription-dep
...