---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: iampolicymember-sample-memberref
spec:
  memberFrom:
    serviceAccountRef:
      name: devops-robot
  role: roles/editor
  resourceRef:
    kind: PubSubTopic
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    name:  pubsubsubscription-dep
...