---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: iampolicy-sample-workloadidentity
spec:
  resourceRef:
    kind: IAMServiceAccount
    name: iampolicy-dep-workloadidentity
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        # replace ${PROJECT_ID} with your project name
        - serviceAccount:jvillarreal-sandbox-360616.svc.id.goog[default/iampolicy-dep-workloadidentity]
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: iampolicy-dep-workloadidentity
spec:
  displayName: Example Service Account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iampolicy-dep-workloadidentity
  annotations:
    # replace jvillarreal-sandbox-360616 with your project name
    iam.gke.io/gcp-service-account: iampolicy-dep-workloadidentity@jvillarreal-sandbox-360616.iam.gserviceaccount.com
...