apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-sample-memberref
spec:
  memberFrom:
    serviceAccountRef:
      name: iampolicymember-dep-memberref
  role: roles/editor
  resourceRef:
    kind: PubSubTopic
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    name: iampolicymember-dep-memberref
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: iampolicymember-dep-memberref
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: iampolicymember-dep-memberref