---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: iampolicy-workloadidentitys
spec:
  resourceRef:
    kind: IAMServiceAccount
    name: devops-robot
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        # replace ${PROJECT_ID} with your project name
        - serviceAccount:jvillarreal-sandbox-360616.svc.id.goog[default/iampolicy-dep-workloadidentity]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iampolicy-dep-workloadidentity
  annotations:
    iam.gke.io/gcp-service-account: devops-robot@jvillarreal-sandbox-360616.iam.gserviceaccount.com
...