---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: iamcustomrolesampleproject
spec:
  title: Example Project-Level Custom Role
  description: This role only contains two permissions - publish and update
  permissions:
    - pubsub.topics.publish
    - pubsub.topics.update
  stage: GA
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: iampolicy-sample-pubsubadmin
spec:
  resourceRef:
    kind: PubSubTopic
    name: pubsubsubscription-dep
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
  bindings:
    - role: roles/editor
      members:
        - serviceAccount:devops-robot@jvillarreal-sandbox-360616.iam.gserviceaccount.com
        - user:joseph.villarreal@66degrees.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: test-iampolicymember
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/jvillarreal-sandbox-360616
  member: serviceAccount:devops-robot@jvillarreal-sandbox.iam.gserviceaccount.com
  role: roles/storage.admin
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: iampartialpolicy-sample-project
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: jvillarreal-sandbox-360616
  bindings:
    - role: roles/storage.admin
      members:
        - member: serviceAccount:serviceAccount:devops-robot@jvillarreal-sandbox.iam.gserviceaccount.com
    # - role: roles/editor
    #   members:
    #     - memberFrom:
    #         serviceAccountRef:
    #           name: joseph
...