apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: iampolicy-sample-external-project
spec:
  resourceRef:
    kind: Project
    external: projects/iampolicy-dep-external-project
  bindings:
    - members:
        - serviceAccount:devops-robot@jvillarreal-sandbox-360616.iam.gserviceaccount.com
      role: roles/owner
    - members:
        - serviceAccount:iampolicy-dep-external-project@iampolicy-dep-external-project.iam.gserviceaccount.com
      role: roles/storage.admin
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: iampolicy-dep-external-project
  name: iampolicy-dep-external-project
---
# Creates a Project resource to demonstrate how an IAMPolicy can reference a
# Project using `external`.
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    cnrm.cloud.google.com/organization-id: "305658411957"
    cnrm.cloud.google.com/auto-create-network: "false"
  name: iampolicy-dep-external-project
spec:
  name: Config Connector Sample
  billingAccountRef:
    # Replace "${BILLING_ACCOUNT_ID?}" with the numeric ID for your billing account
    external: "0078AA-34EC5B-80DDA4"