---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-demo
  name: pubsubsubscription-dep
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-demo
  name: pubsubsubscription-dep2
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-demo
  labels:
    label-one: "value-one"
  name: pubsubsubscription-sample
spec:
  ackDeadlineSeconds: 15
  messageRetentionDuration: 86400s
  retainAckedMessages: false
  topicRef:
    name: pubsubsubscription-dep
  deadLetterPolicy:
    deadLetterTopicRef:
      name: pubsubsubscription-dep2
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-demo
  name: xxx
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: pubsubsubscription-dep
  member: user:joseph.villarreal@66degrees.com
  role: roles/pubsub.editor

# roles/pubsub.admin
# roles/pubsub.editor
# roles/pubsub.publisher
# roles/pubsub.serviceAgent
# roles/pubsub.subscriber
# roles/pubsub.viewer