---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: secretmanager.googleapis.com
spec:
  projectRef:
    external: projects/jvillarreal-sandbox-360616
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: sensitive1
spec:
  replication:
    automatic: true
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-360616
  name: sensitive1v1
spec:
  enabled: true
  secretData:
    valueFrom:
      secretKeyRef:
        key: secretData
        name: token
  secretRef:
    name: token

---
apiVersion: v1
kind: Secret
metadata:
  name: jvillarreal
data:
  secretData: YnkK #aGkK
