---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: containernodepool-sample-soletenancy
  namespace: iac
spec:
  location: us-central1-b
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 3
  nodeConfig:
    machineType: n1-standard-2
    nodeGroupRef:
      name: containercluster-vpcnative
  clusterRef:
    name: containercluster-vpcnative
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNodeGroup
metadata:
  name: containercluster-vpcnative
  namespace: iac
spec:
  description: A single sole-tenant node in the us-central1-b zone.
  size: 1
  nodeTemplateRef:
    name: containercluster-vpcnative
  zone: us-central1-b
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNodeTemplate
metadata:
  name: containercluster-vpcnative
  namespace: iac
spec:
  region: us-central1
  nodeType: n1-node-96-624