---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: containercluster-dep-vpcnative
  namespace: iac
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false