apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-gcp-secrets
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      # parameters:
      #   - name: secrets[0].key
      #     value: clusters
      #   - name: secrets[0].name
      #     value: clusters
      #   - name: secrets[0].secretKey
          # value: clusters
      valueFiles:
        - values.yaml
    path: helm/helm-gcp-secrets
    repoURL: git@github.com:Lapeyus/IDP.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - Replace=false
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true