apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-gcp-secrets
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        refreshInterval: "10s"
        # secrets:
        #   - key: gcp-secret
        #     name: cluster-secret
        #     secretKey: value
        #   - key: gcp-secret2
        #     name: cluster-secret2
        #     secretKey: value
    path: helm/helm-gcp-secrets
    repoURL: git@github.com:Lapeyus/IDP.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - Replace=false
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true