# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prod
#   namespace: default
# spec:
#   destination:
#     namespace: default
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     directory:
#       jsonnet: {}
#       recurse: true
#     path: envs/prod
#     repoURL: git@github.com:Lapeyus/IDP.git
#     targetRevision: HEAD
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     retry:
#       backoff:
#         duration: 5s
#         factor: 2
#         maxDuration: 3m0s
#       limit: 2
#     syncOptions:
#     - Replace=true