---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-demo
  name: cutomroletestargo
  namespace: iac
spec:
  title: Example Project-Level Custom Role
  description: This role only contains two permissions - publish and update
  permissions:
    - pubsub.topics.publish
    - pubsub.topics.update
  stage: GA