---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jvillarreal-sandbox-demo
  name: iamcustomrole-dep-project
  namespace: iac