---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: 'true'
  name: containercluster-vpcnative
  namespace: iac
spec:
  addonsConfig:
    configConnectorConfig:
      enabled: true
    dnsCacheConfig:
      enabled: true
    gcePersistentDiskCsiDriverConfig:
      enabled: true
    networkPolicyConfig:
      disabled: false
  clusterAutoscaling:
    autoProvisioningDefaults:
      oauthScopes:
        - 'https://www.googleapis.com/auth/logging.write'
        - 'https://www.googleapis.com/auth/monitoring'
      serviceAccountRef:
        external: default
    autoscalingProfile: BALANCED
    enabled: true
    resourceLimits:
      - maximum: 100
        minimum: 10
        resourceType: cpu
      - maximum: 1000
        minimum: 100
        resourceType: memory
  clusterIpv4Cidr: 10.4.0.0/16
  clusterTelemetry:
    type: ENABLED
  databaseEncryption:
    state: DECRYPTED
  defaultMaxPodsPerNode: 16
  defaultSnatStatus:
    disabled: false
  description: >-
    A large regional VPC-native cluster set up with special networking
    considerations.
  enableBinaryAuthorization: true
  enableIntranodeVisibility: true
  enableShieldedNodes: true
  initialNodeCount: 1
  ipAllocationPolicy:
    clusterIpv4CidrBlock: 10.4.0.0/16
    clusterSecondaryRangeName: clusterrange
    servicesIpv4CidrBlock: 10.3.0.0/16
    servicesSecondaryRangeName: servicesrange
  location: us-central1
  loggingConfig:
    enableComponents:
      - SYSTEM_COMPONENTS
      - WORKLOADS
  loggingService: logging.googleapis.com/kubernetes
  maintenancePolicy:
    dailyMaintenanceWindow:
      duration: PT4H0M0S
      startTime: '00:00'
  monitoringConfig:
    enableComponents:
      - SYSTEM_COMPONENTS
  monitoringService: monitoring.googleapis.com/kubernetes
  networkPolicy:
    enabled: true
  networkRef:
    name: containercluster-dep-vpcnative
  networkingMode: VPC_NATIVE
  nodeLocations:
    - us-central1-a
    - us-central1-b
    - us-central1-c
    - us-central1-f
  nodeVersion: 1.22.10-gke.900
  notificationConfig:
    pubsub:
      enabled: true
      topicRef:
        name: containercluster-dep-vpcnative
  podSecurityPolicyConfig:
    enabled: true
  releaseChannel:
    channel: STABLE
  resourceID: containercluster-vpcnative
  subnetworkRef:
    name: containercluster-dep-vpcnative
  verticalPodAutoscaling:
    enabled: true
  workloadIdentityConfig:
    workloadPool: jvillarreal-sandbox-360616.svc.id.goog