---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNodeGroup
metadata:
  name: containercluster-vpcnative
  namespace: iac
spec:
  description: A single sole-tenant node in the us-central1-b zone.
  size: 1
  nodeTemplateRef:
    name: containercluster-vpcnative
  zone: us-central1-b