apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: iac
    server: 'https://kubernetes.default.svc'
  source:
    path: gcp/stage
    repoURL: 'git@github.com:Lapeyus/IDP.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - RespectIgnoreDifferences=true
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=false
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
